name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t playwright:latest .

    - name: Save Docker image to file
      run: |
        docker save playwright:latest | gzip > playwright_latest.tar.gz

    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v2
      with:
        name: playwright-image
        path: playwright_latest.tar.gz

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Docker image artifact
      uses: actions/download-artifact@v2
      with:
        name: playwright-image
        path: playwright_latest.tar.gz

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy Docker image to EC2
      env:
        EC2_DNS: ${{ secrets.EC2_DNS }}
      run: |
        scp -o StrictHostKeyChecking=no playwright_latest.tar.gz ubuntu@$EC2_DNS:/home/ubuntu/

    - name: Load Docker image on EC2 and run tests
      env:
        EC2_DNS: ${{ secrets.EC2_DNS }}
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@$EC2_DNS "gzip -d /home/ubuntu/playwright_latest.tar.gz && docker load < /home/ubuntu/playwright_latest.tar && docker run playwright:latest"
